name: "CI"
author: "ixuz"
inputs:
  github-token:
    required: true
  sonar-token:
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/checkout@v3
      with:
        node-version: "16"
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Build project
      run: yarn build
    - name: Test project
      run: yarn test
    - name: SonarCloud scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        SONAR_TOKEN: ${{ inputs.sonar-token }}
