name: "Publish"
author: "ixuz"
inputs:
  github-token:
    required: true
  npm-token:
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install deps
      run: yarn install --frozen-lockfile
    - name: Lint
      run: yarn lint
    - name: Build
      run: yarn build
    - name: Test
      run: yarn test
    - name: Publish
      run: yarn publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
