name: "Publish"
author: "ixuz"
inputs:
  github-token:
    required: true
  npm-token:
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install deps, build and test
      shell: bash
      env:
        NPM_TOKEN: ${{ inputs.npm-token }}
      run: |
        yarn install --frozen-lockfile
        yarn lint
        yarn build
        yarn test
        yarn publish --access public
