name: "Publish"
author: "ixuz"
inputs:
  github-token:
    required: true
  sonar-token:
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install deps, build and test
      shell: bash
      run: |
        yarn install --frozen-lockfile
        yarn build
        yarn test
        yarn publish --access public
