name: "Release"
author: "ixuz"
inputs:
  github-token:
    required: true
  npm-token:
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        node-version: 16.x
        registry-url: 'https://registry.npmjs.org'
    - name: Git config
      shell: bash
      run: |
        git config --global user.name "Antwika"
        git config --global user.email "<>"
    - name: Install deps
      shell: bash
      run: yarn install --frozen-lockfile
    - name: Tag release
      shell: bash
      run: yarn release
    - name: Lint
      shell: bash
      run: yarn lint
    - name: Build
      shell: bash
      run: yarn build
    - name: Test
      shell: bash
      run: yarn test
    - name: Commit
      shell: bash
      run: git push --follow-tags origin main
    - name: Publish
      shell: bash
      run: yarn publish --access public
      env:
        NPM_AUTH_TOKEN: ${{ inputs.npm-token }}
